### ISSUE TITLE
Can MonCraft support android and ios

### ISSUE THREAD

**Issue by takaaptech** [OopsOverflow/MonCraft#42]
Hi @OopsOverflow with current tech and Dependencies, can we build MonCraft to android and ios for play?
Thank you so much!

**Comment by OopsOverflow** [comment]
Hello @takaaptech !

Although MonCraft is quite an optimised game, we do not target Android & iOS for the moment. 
OpenGL is not natively supported on Android or iOS, so we have to migrate to Vulkan or GLES.
You can still enjoy the game on Windows, Linux and MacOS though!

After discussion with the MonCraft team, support for mobile devices might come September this year or later. So keep an eye on the repo! We're actively adding new features.

**Comment by takaaptech** [comment]
Thank @OopsOverflow for the update! I can't wait to see MonCraft on Android and iOS device
Keep up your good work!

**Comment by OopsOverflow** [comment]
You're welcome @takaaptech ! 
MonCraft is also open for contributions! Consider contributing this open source project. 

Cheers!
